Vagrant.configure("2") do |config|

  config.vm.box = "raring64"
  config.vm.host_name = "php-e-seus-demonios"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.synced_folder("..", "/opt/psd", :mount_options => ['dmode=777','fmode=777'])
  config.vm.provision "shell", path: "Provisioner"

end
